//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogonVistaOrbInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogonVistaOrbInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;RegistrationInfo&gt;
        ///    &lt;Date&gt;2024-08-11T00:48:32.8953235&lt;/Date&gt;
        ///    &lt;Author&gt;xxxman360,Benj2557&lt;/Author&gt;
        ///    &lt;URI&gt;\LogonVistaOrb&lt;/URI&gt;
        ///  &lt;/RegistrationInfo&gt;
        ///  &lt;Triggers&gt;
        ///    &lt;EventTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;System&quot;&amp;gt;&amp;lt;Select Path=&quot;System&quot;&amp;gt;*[System[EventID=1074]]&amp;lt;/Select&amp;gt;&amp;lt;/Query&amp;gt;&amp;lt;/Que [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LogonVistaOrb {
            get {
                return ResourceManager.GetString("LogonVistaOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///	&lt;RegistrationInfo&gt;
        ///		&lt;Date&gt;2024-12-03T00:55:36.1040963&lt;/Date&gt;
        ///		&lt;Author&gt;Benj2557&lt;/Author&gt;
        ///		&lt;URI&gt;\LogonVistaOrb-Lock&lt;/URI&gt;
        ///	&lt;/RegistrationInfo&gt;
        ///	&lt;Triggers&gt;
        ///		&lt;SessionStateChangeTrigger&gt;
        ///			&lt;Enabled&gt;true&lt;/Enabled&gt;
        ///			&lt;StateChange&gt;SessionLock&lt;/StateChange&gt;
        ///		&lt;/SessionStateChangeTrigger&gt;
        ///	&lt;/Triggers&gt;
        ///	&lt;Principals&gt;
        ///		&lt;Principal id=&quot;Author&quot;&gt;
        ///			&lt;GroupId&gt;S-1-5-32-544&lt;/GroupId&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LogonVistaOrbLock {
            get {
                return ResourceManager.GetString("LogonVistaOrbLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///	&lt;RegistrationInfo&gt;
        ///		&lt;Date&gt;2024-12-03T00:55:36.1040963&lt;/Date&gt;
        ///		&lt;Author&gt;Benj2557&lt;/Author&gt;
        ///		&lt;URI&gt;\LogonVistaOrb-Logoff&lt;/URI&gt;
        ///	&lt;/RegistrationInfo&gt;
        ///	&lt;Triggers&gt;
        ///		&lt;EventTrigger&gt;
        ///			&lt;Enabled&gt;true&lt;/Enabled&gt;
        ///			&lt;Subscription&gt;&amp;lt;QueryList&amp;gt;&amp;lt;Query Id=&quot;0&quot; Path=&quot;Security&quot;&amp;gt;&amp;lt;Select Path=&quot;Security&quot;&amp;gt;*[System[EventID=4647]]&amp;lt;/Select&amp;gt;&amp;lt;/Query&amp;gt;&amp;lt;/QueryList&amp;gt;&lt;/Subs [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LogonVistaOrbLogoff {
            get {
                return ResourceManager.GetString("LogonVistaOrbLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;RegistrationInfo&gt;
        ///    &lt;Date&gt;2024-12-03T00:55:36.1040963&lt;/Date&gt;
        ///    &lt;Author&gt;Benj2557&lt;/Author&gt;
        ///    &lt;URI&gt;\LogonVistaOrb-Logon&lt;/URI&gt;
        ///  &lt;/RegistrationInfo&gt;
        ///  &lt;Triggers&gt;
        ///    &lt;LogonTrigger&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///    &lt;/LogonTrigger&gt;
        ///  &lt;/Triggers&gt;
        ///  &lt;Principals&gt;
        ///    &lt;Principal id=&quot;Author&quot;&gt;
        ///      &lt;GroupId&gt;S-1-5-32-544&lt;/GroupId&gt;
        ///      &lt;RunLevel&gt;HighestAvailable&lt;/RunLevel&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LogonVistaOrbLogon {
            get {
                return ResourceManager.GetString("LogonVistaOrbLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///	&lt;RegistrationInfo&gt;
        ///		&lt;Date&gt;2024-12-03T00:55:36.1040963&lt;/Date&gt;
        ///		&lt;Author&gt;Benj2557&lt;/Author&gt;
        ///		&lt;URI&gt;\LogonVistaOrb-Unlock&lt;/URI&gt;
        ///	&lt;/RegistrationInfo&gt;
        ///	&lt;Triggers&gt;
        ///		&lt;SessionStateChangeTrigger&gt;
        ///			&lt;Enabled&gt;true&lt;/Enabled&gt;
        ///			&lt;StateChange&gt;SessionUnlock&lt;/StateChange&gt;
        ///		&lt;/SessionStateChangeTrigger&gt;
        ///	&lt;/Triggers&gt;
        ///	&lt;Principals&gt;
        ///		&lt;Principal id=&quot;Author&quot;&gt;
        ///			&lt;GroupId&gt;S-1-5-32-544&lt;/Grou [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LogonVistaOrbUnlock {
            get {
                return ResourceManager.GetString("LogonVistaOrbUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] segoeuisl {
            get {
                object obj = ResourceManager.GetObject("segoeuisl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Shutdown {
            get {
                return ResourceManager.GetStream("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream WAVE5051 {
            get {
                return ResourceManager.GetStream("WAVE5051", resourceCulture);
            }
        }
    }
}
